import type { Metadata } from "next";
import { Fredoka } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const providenceSansBold = localFont({
  src: "../public/font/Providence-SansBold.otf",
  variable: "--font-providenceSansBold",
});

const providenceSans = localFont({
  src: "../public/font/Providence-Sans.ttf",
  variable: "--font-providenceSans",
});

const fredoka = Fredoka({
  subsets: ["latin"],
  variable: "--font-fredoka",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${fredoka.variable}
          ${providenceSans.variable}
          ${providenceSansBold.variable}
        `}
      >
        {children}
      </body>
    </html>
  );
}